# Generated by Django 5.2.7 on 2025-11-04 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualitydata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='airqualitydata',
            unique_together={('station_id', 'timestamp')},
        ),
    ]
